# Generated by Django 3.2.24 on 2024-02-26 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monapp', '0003_auto_20240226_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='annonceur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
